repos:
  - repo: local
    hooks:
      - id: go-fmt
        name: Run go fmt in Docker
        entry: docker run --rm -v $(pwd):/src/src/ -w /src monkey-lang-monkey-lang-1 gofmt -w .
        language: system
        pass_filenames: false
      - id: go-vet
        name: Run go vet in Docker
        entry: docker run --rm -v $(pwd):/src/src/ -w /src  monkey-lang-monkey-lang-1 go vet ./...
        language: system
        pass_filenames: false
